### ISSUE TITLE
Error with dataframe in filter_allele_table.R

### ISSUE THREAD

**Issue by Walwa** [wanyuac/PAMmaker#9]
Hi and Thank you for this great software.
Unfortunately I am having a problem in the checking reliability of SRST2 allele calling. I am using a pubmlst 7 allele protocol. When running the R script I get :
Rscript /home/me/PAMmaker/reliability/filter_allele_table.R --profiles summary__compiledResults.txt --scores mergedScores__gene.scores --output Pan_srst2__reliableCalls
Error in `[.data.frame`(x, , c(1, (which(names(x) == "maxMAF") + 1):ncol(x))) : 
  undefined columns selected
Calls: rmMLST -> [ -> [.data.frame
When I look at the columns they are :
Sample	ST	glpF	sigF	glpT	Natrans	rpoB	ftsA	clpC	mismatches	uncertainty	depth	maxMAF
Do I need to remove some columns or rename them?

**Comment by wanyuac** [comment]
Hi Walwa,
This script does not process MLST information (`MLST information in the input table of allele calls (specified by the --profiles option) will not be processed by this script.`) directly or you may convert the MLST database into an SRST2-compatible format and use the gene-detection mode of SRST2 to generate results for this script. Hope this helps.
Regards

**Comment by wanyuac** [comment]
No further response from the issue submitter
